### ISSUE TITLE
Error starting UI

### ISSUE THREAD

**Issue by andrewsu** [TranslatorSRI/Benchmarks#17]
when I execute `python server.py` (as described in https://github.com/TranslatorSRI/Benchmarks/blob/main/README.md#ui), I get the following error:

```
$ python server.py
Traceback (most recent call last):
  File "/home/asu/Science/Benchmarks/server.py", line 126, in <module>
    APP.mount("/", StaticFiles(directory="ui/build/", html=True), name="ui")
  File "/home/asu/env/benchmark/lib/python3.10/site-packages/starlette/staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'ui/build/' does not exist
```

Is there a build step that I missed?

**Comment by andrewsu** [comment]
I got a bit further by doing `cd ui; npm install`, but still got errors on `npm run build`. Going to assume that the UI has just gone out of support...
