### ISSUE TITLE
Missing module in install

### ISSUE THREAD

**Issue by dkoslicki** [TranslatorSRI/Benchmarks#32]
Repro:
```
 git clone https://github.com/TranslatorSRI/Benchmarks.git
 cd Benchmarks
 conda create -n bench -y python=3.9
 conda activate bench
 pip install -e .
 benchmarks_fetch --help
```
results in:
```
Traceback (most recent call last):
  File "/home/faculty/dmk333/miniforge3/envs/bench/bin/benchmarks_fetch", line 33, in <module>
    sys.exit(load_entry_point('benchmarks-runner', 'console_scripts', 'benchmarks_fetch')())
  File "/home/faculty/dmk333/miniforge3/envs/bench/bin/benchmarks_fetch", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/faculty/dmk333/miniforge3/envs/bench/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/faculty/dmk333/miniforge3/envs/bench/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/scratch/dmk333_new/Repositories/Benchmarks/benchmarks_runner/__init__.py", line 1, in <module>
    from .main import run_benchmarks
  File "/scratch/dmk333_new/Repositories/Benchmarks/benchmarks_runner/main.py", line 6, in <module>
    from benchmarks_runner.request import fetch_results
  File "/scratch/dmk333_new/Repositories/Benchmarks/benchmarks_runner/request.py", line 12, in <module>
    from reasoner_pydantic import Response
ModuleNotFoundError: No module named 'reasoner_pydantic'
```

**Comment by maximusunc** [comment]
OBE. reasoner_pydantic is no longer being used.
